
checkout:
	svn co https://version-control.adelaide.edu.au/svn/SEPADL15S2PG19/DemonTest
	
update:
	svn update
	
jar:
	ant jar
compile:
	ant compile
copyRes:
	ant copyRes
clean:
	ant clean
upload:
	ant upload
remoteRun:
	ant remoteRun
run:
	ant run
test:
	ant test
dist:
	ant dist	

